### ✅ Sucesso: CEP válido com dados encontrados
GET https://weather-api-181365624128.us-central1.run.app/weather?cep=01001-000
Accept: application/json

### ❌ Erro: CEP com formato inválido
GET https://weather-api-181365624128.us-central1.run.app/weather?cep=abc-defg
Accept: application/json

### ❌ Erro: CEP não informado
GET https://weather-api-181365624128.us-central1.run.app/weather
Accept: application/json

